### ISSUE TITLE
Video name + saving place

### ISSUE THREAD

**Issue by IGDT** [fldvrees/Ad-fundum-timer#1]
Hello,

How can we change the place where the recorded videos are stored?
And how do we change the name of the videos?

Kind regards

**Comment by FlorisDevreese** [comment]
hi @IGDT 

it downloads the video in the default download location of your browser.
so to change the download location, you have to change the default download location in your browser.

to change the name of the file, you have to change [this code block](https://github.com/FlorisDevreese/Ad-fundum-timer/blob/52c77b5bbfd0dd7a84f5b2692e5966bae223dc8e/RecordRTC.js#L1819C52-L1835).

> **Note**
> this repo is archived, which mean i don't maintain this anymore, and i don't know if this still works.
